SELECT
  DA.AREA_NAME,
  SUM(FT.GETON_5MIN_POPULATION_MAX) AS "5분이내 승차 인원",
  SUM(FT.GETOFF_5MIN_POPULATION_MAX) AS "5분이내 하차 인원"
FROM
  FACT.FACT_TRANSPORT FT
  JOIN DIM.DIM_AREA DA ON FT.AREA_ID = DA.AREA_CODE
WHERE
  FT.TIME_KEY = (
    SELECT
      MAX(TIME_KEY)
    FROM
      FACT.FACT_TRANSPORT
  )
GROUP BY
  DA.AREA_NAME
ORDER BY
  SUM(FT.GETON_5MIN_POPULATION_MAX) DESC
LIMIT
  10;