WITH -- 현재 시각 기준 24시간 정각 생성 CTE
  PREV_HOURS AS (
    SELECT
      DATE_TRUNC('HOUR', DATETIME_VALUE) AS HOUR_TIMESTAMP
    FROM
      DIM.DIM_TIME
    WHERE
      DATETIME_VALUE BETWEEN DATEADD(HOUR, -23, GETDATE()) AND GETDATE()
  )
SELECT
  PH.HOUR_TIMESTAMP AS "시간",
  ROUND(AVG(FW.TEMPERATURE), 1) AS "온도",
  ROUND(AVG(FW.SENSIBLE_TEMPERATURE), 1) AS "체감온도",
  ROUND(AVG(FW.HUMIDITY), 1) AS "습도"
FROM
  PREV_HOURS PH
  LEFT JOIN DIM.DIM_TIME DT ON DATE_TRUNC('HOUR', PH.HOUR_TIMESTAMP) = DATE_TRUNC('HOUR', DT.DATETIME_VALUE)
  LEFT JOIN FACT.FACT_WEATHER FW ON DT.TIME_KEY = FW.TIME_KEY
GROUP BY
  PH.HOUR_TIMESTAMP
ORDER BY
  PH.HOUR_TIMESTAMP;