WITH
  UNIQUE_EVENT_REGIONS AS (
    SELECT DISTINCT
      FACT.EVENT_ID,
      FACT.AREA_ID,
      SUBSTRING(FACT.EVENT_PERIOD, 1, 10) AS EVENT_PERIOD_START_STR,
      SUBSTRING(FACT.EVENT_PERIOD, 12, 10) AS EVENT_PERIOD_END_STR
    FROM
      FACT.FACT_EVENT FACT
      JOIN DIM.DIM_EVENT DIM ON FACT.EVENT_ID = DIM.EVENT_ID
  )
SELECT
  DAG.AREA_NAME AS "장소명",
  COUNT(*) AS "문화행사 수"
FROM
  UNIQUE_EVENT_REGIONS UER
  JOIN DIM.DIM_AREA_GEOJSON DAG ON UER.AREA_ID = DAG.AREA_ID
WHERE
  CURRENT_DATE BETWEEN UER.EVENT_PERIOD_START_STR::DATE AND UER.EVENT_PERIOD_END_STR::DATE
GROUP BY
  DAG.AREA_NAME
ORDER BY
  "문화행사 수" DESC
LIMIT
  10;