WITH CURR_RSB AS ( -- 가장 최근의 FACT_COMMERCIAL ROWS 들의 ID
    SELECT
        FACT_COMMERCIAL_ID
    FROM
        FACT.FACT_COMMERCIAL
    WHERE
        TO_TIMESTAMP(TIME_KEY::TEXT, 'YYYYMMDDHH24MI') = (
            SELECT
                MAX(TO_TIMESTAMP(TIME_KEY::TEXT, 'YYYYMMDDHH24MI'))
            FROM
                FACT.FACT_COMMERCIAL
            WHERE
                TO_TIMESTAMP(TIME_KEY::TEXT, 'YYYYMMDDHH24MI') <= GETDATE()
        )
),
CATEGORY_DATA AS (
    SELECT
        DC.CATEGORY_LARGE AS CATEGORY_LARGE, 
        DC.CATEGORY_MEDIUM AS CATEGORY_MEDIUM, 
        SUM(FCR.CATEGORY_PAYMENT_COUNT) AS TOTAL_PAYMENT_COUNT,
        AVG(FCR.CATEGORY_PAYMENT_MAX) AS AVG_MAX_PAYMENT_AMOUNT 
    FROM
        FACT.FACT_COMMERCIAL_RSB FCR
        JOIN DIM.DIM_CATEGORY DC ON FCR.CATEGORY_ID = DC.CATEGORY_ID
    WHERE
        FCR.FACT_COMMERCIAL_ID IN (
            SELECT
                FACT_COMMERCIAL_ID
            FROM
                CURR_RSB
        )
    GROUP BY
        DC.CATEGORY_LARGE,
        DC.CATEGORY_MEDIUM
)
SELECT
    CATEGORY_LARGE AS "대분류", 
    CATEGORY_MEDIUM AS "중분류",
    TOTAL_PAYMENT_COUNT AS "결제 건수(합계)", 
    ROUND(AVG_MAX_PAYMENT_AMOUNT/10000) AS "업종별 최대 결제 금액(평균)"
FROM
    CATEGORY_DATA
ORDER BY
    SUM(AVG_MAX_PAYMENT_AMOUNT) OVER (PARTITION BY CATEGORY_LARGE) DESC,
    CATEGORY_MEDIUM;