WITH 
  CURR_RSB AS ( -- 가장 최근의 FACT_COMMERCIAL ROWS 들의 ID
    SELECT
      FACT_COMMERCIAL_ID
    FROM
      FACT.FACT_COMMERCIAL
    WHERE
      TO_TIMESTAMP(TIME_KEY::TEXT, 'YYYYMMDDHH24MI') = (
        SELECT 
          MAX(TO_TIMESTAMP(TIME_KEY::TEXT, 'YYYYMMDDHH24MI'))
        FROM
          FACT.FACT_COMMERCIAL
        WHERE
          TO_TIMESTAMP(TIME_KEY::TEXT, 'YYYYMMDDHH24MI') <= GETDATE()
      )
  )
    
SELECT
  DC.CATEGORY_LARGE AS "대분류",
  DC.CATEGORY_MEDIUM AS "중분류",
  SUM(FCR.CATEGORY_PAYMENT_COUNT) AS "결제 건수(합계)",
  AVG(FCR.CATEGORY_PAYMENT_MAX) AS "업종별 최대 결제 금액(평균)"
FROM
  FACT.FACT_COMMERCIAL_RSB FCR
  JOIN DIM.DIM_CATEGORY DC ON FCR.CATEGORY_ID = DC.CATEGORY_ID
WHERE
  FCR.FACT_COMMERCIAL_ID IN (
    SELECT
      FACT_COMMERCIAL_ID
    FROM
      CURR_RSB
  )
GROUP BY
  DC.CATEGORY_LARGE,
  DC.CATEGORY_MEDIUM
ORDER BY
  SUM(CATEGORY_PAYMENT_COUNT) DESC;