WITH
  CURR_POP AS (
    SELECT
      *
    FROM
      FACT.FACT_POPULATION FP
    WHERE
      FP.TIME_KEY = (
        SELECT
          MAX(TIME_KEY)
        FROM
          FACT.FACT_POPULATION
      )
  )
SELECT
  DA.AREA_NAME AS "장소명",
  (CP.POPULATION_MAX + CP.POPULATION_MIN) / 2 AS "평균 유동 인구"
FROM
  CURR_POP CP
  JOIN DIM.DIM_AREA DA ON DA.AREA_ID = CP.AREA_ID
ORDER BY
  (CP.POPULATION_MAX + CP.POPULATION_MIN) / 2 DESC
LIMIT
  10;