WITH
  WEEK_RANGE AS (
    SELECT
      DATE_TRUNC('WEEK', GETDATE()) - INTERVAL '7 DAYS' AS START_OF_LAST_WEEK,
      DATE_TRUNC('WEEK', GETDATE()) - INTERVAL '1 SECONDS' AS END_OF_LAST_WEEK
  )
SELECT
  CASE DT.DAY_NAME    
    WHEN 'Monday' THEN '월요일'
    WHEN 'Tuesday' THEN '화요일'
    WHEN 'Wednesday' THEN '수요일'
    WHEN 'Thursday' THEN '목요일'
    WHEN 'Friday' THEN '금요일'
    WHEN 'Saturday' THEN '토요일'
    WHEN 'Sunday' THEN '일요일'
  END AS "요일",
  ROUND(AVG(FW.TEMPERATURE), 1) AS "평균 기온",
  ROUND(MAX(FW.MAX_TEMPERATURE), 1) AS "최고 기온",
  ROUND(MIN(FW.MIN_TEMPERATURE), 1) AS "최저 기온"
FROM
  FACT.FACT_WEATHER FW
  JOIN DIM.DIM_TIME DT ON FW.TIME_KEY = DT.TIME_KEY
  JOIN DIM.DIM_AREA DA ON FW.AREA_ID = DA.AREA_ID
  JOIN WEEK_RANGE WR ON DT.DATE_VALUE BETWEEN WR.START_OF_LAST_WEEK AND WR.END_OF_LAST_WEEK
WHERE
  1 = 1 [[
    AND DA.AREA_NAME = {{AREA_NAME}}
]]
GROUP BY
  "요일",
  DT.DAY_NAME
ORDER BY
  CASE DT.DAY_NAME
    WHEN 'Monday' THEN 1
    WHEN 'Tuesday' THEN 2
    WHEN 'Wednesday' THEN 3
    WHEN 'Thursday' THEN 4
    WHEN 'Friday' THEN 5
    WHEN 'Saturday' THEN 6
    WHEN 'Sunday' THEN 7
  END;