WITH
  WEEK_RANGE AS (
    SELECT
      DATE_TRUNC('WEEK', GETDATE()) - INTERVAL '7 DAYS' AS START_OF_LAST_WEEK,
      DATE_TRUNC('WEEK', GETDATE()) - INTERVAL '1 SECONDS' AS END_OF_LAST_WEEK
  ),
  BASE_DATA AS (
    SELECT
      DC.CATEGORY_LARGE AS "대분류",
      DC.CATEGORY_MEDIUM AS "중분류",
      SUM(FCR.CATEGORY_PAYMENT_COUNT) AS "결제 건수(합계)",
      AVG(FCR.CATEGORY_PAYMENT_MAX) AS "업종별 최대 결제 금액(평균)"
    FROM
      FACT.FACT_COMMERCIAL_RSB FCR
      JOIN FACT.FACT_COMMERCIAL FC ON FCR.FACT_COMMERCIAL_ID = FC.FACT_COMMERCIAL_ID
      JOIN DIM.DIM_CATEGORY DC ON FCR.CATEGORY_ID = DC.CATEGORY_ID
      JOIN WEEK_RANGE WR ON TO_TIMESTAMP(FC.TIME_KEY::TEXT, 'YYYYMMDDHH24MI') BETWEEN WR.START_OF_LAST_WEEK AND WR.END_OF_LAST_WEEK
      JOIN DIM.DIM_AREA DA ON FC.AREA_ID = DA.AREA_ID
    WHERE
      1 = 1
      AND [[
    DA.AREA_NAME = {{AREA_NAME}}
    ]]
    GROUP BY
      DC.CATEGORY_LARGE,
      DC.CATEGORY_MEDIUM
  )
SELECT
  "대분류",
  "중분류",
  "결제 건수(합계)",
  "업종별 최대 결제 금액(평균)"
FROM
  BASE_DATA
ORDER BY
  SUM("결제 건수(합계)") OVER (
    PARTITION BY
      "대분류"
  ) DESC,
  "중분류";

