
SELECT
  DA.AREA_NAME AS "장소명",
  DT.DATE_VALUE AS "기준시각", 
  CASE DT.DAY_NAME
    WHEN 'Monday' THEN '월요일'
    WHEN 'Tuesday' THEN '화요일'
    WHEN 'Wednesday' THEN '수요일'
    WHEN 'Thursday' THEN '목요일'
    WHEN 'Friday' THEN '금요일'
    WHEN 'Saturday' THEN '토요일'
    WHEN 'Sunday' THEN '일요일'
    ELSE DT.DAY_NAME
  END AS "요일",
  SUM(FP.POPULATION_MAX) / 10000 AS "유동 인구",
  AVG(FC.TOTAL_PAYMENT_COUNT) AS "결제 건수(신한)",
  AVG(FC.PAYMENT_AMOUNT_MAX) / 10000 AS "결제 금액(최대)"
FROM
  DIM.DIM_TIME DT
  LEFT JOIN FACT.FACT_POPULATION FP ON DT.TIME_KEY = FP.TIME_KEY
  LEFT JOIN FACT.FACT_COMMERCIAL FC ON DT.TIME_KEY = FC.TIME_KEY
  LEFT JOIN DIM.DIM_AREA DA ON FC.AREA_ID = DA.AREA_ID
WHERE
  DT.DATE_VALUE BETWEEN (DATE_TRUNC('week', GETDATE()) - INTERVAL '7 days') 
                    AND (DATE_TRUNC('week', GETDATE()) - INTERVAL '1 second')
  AND [[ DA.AREA_NAME = {{AREA_NAME}} ]]
GROUP BY
  DA.AREA_NAME,
  DT.DATE_VALUE,
  DT.DAY_NAME,
  DT.IS_WEEKEND
ORDER BY
  DT.DATE_VALUE;