WITH
  WEEK_RANGE AS (
    SELECT
      DATE_TRUNC('WEEK', GETDATE()) - INTERVAL '7 DAYS' AS START_OF_LAST_WEEK,
      DATE_TRUNC('WEEK', GETDATE()) - INTERVAL '1 SECOND' AS END_OF_LAST_WEEK
  )
SELECT
  DT.HOUR AS "시각",
  ROUND(
    AVG(
      (
        FT.GETON_10MIN_POPULATION_MIN + FT.GETON_10MIN_POPULATION_MAX
      ) / 2.0
    )
  ) AS "승차 평균",
  ROUND(
    AVG(
      (
        FT.GETOFF_10MIN_POPULATION_MIN + FT.GETOFF_10MIN_POPULATION_MAX
      ) / 2.0
    )
  ) AS "하차 평균"
FROM
  FACT.FACT_TRANSPORT AS FT
  JOIN DIM.DIM_TIME AS DT ON FT.TIME_KEY = DT.TIME_KEY
  JOIN DIM.DIM_AREA AS AREA ON FT.AREA_ID = AREA.AREA_CODE
  JOIN WEEK_RANGE WR ON DT.DATE_VALUE BETWEEN WR.START_OF_LAST_WEEK AND WR.END_OF_LAST_WEEK
WHERE
  DT.HOUR BETWEEN 8 AND 22  [[AND AREA.AREA_NAME = {{AREA_NAME}}]]
GROUP BY
  DT.HOUR
ORDER BY
  DT.HOUR;