WITH
  WEEK_RANGE AS (
    SELECT
      DATE_TRUNC('WEEK', GETDATE()) - INTERVAL '7 DAYS' AS START_OF_PREV_WEEK,
      DATE_TRUNC('WEEK', GETDATE()) - INTERVAL '1 SECONDS' AS END_OF_PREV_WEEK
  )
SELECT
  DA.CATEGORY AS "장소 카테고리",
  DC.CATEGORY_LARGE AS "대분류",
  SUM(TOTAL_PAYMENT_COUNT) / 10000 AS "결제 건수(합계)"
FROM
  FACT.FACT_COMMERCIAL FC
  JOIN FACT.FACT_COMMERCIAL_RSB FCR ON FC.FACT_COMMERCIAL_ID = FCR.FACT_COMMERCIAL_ID
  JOIN DIM.DIM_AREA DA ON FC.AREA_ID = DA.AREA_ID
  JOIN DIM.DIM_TIME DT ON FC.TIME_KEY = DT.TIME_KEY
  JOIN WEEK_RANGE WR ON DT.DATE_VALUE BETWEEN WR.START_OF_PREV_WEEK AND WR.END_OF_PREV_WEEK
  JOIN DIM.DIM_CATEGORY DC ON DC.CATEGORY_ID = FCR.CATEGORY_ID
GROUP BY
  DA.CATEGORY,
  DC.CATEGORY_LARGE
ORDER BY
  CATEGORY;