WITH
  WEEK_RANGE AS ( 
    SELECT
      DATE_TRUNC('WEEK', GETDATE()) - INTERVAL '7 DAYS' AS START_OF_LAST_WEEK,
      DATE_TRUNC('WEEK', GETDATE()) - INTERVAL '1 SECOND' AS END_OF_LAST_WEEK
  )  
SELECT
  DA.AREA_NAME AS "장소명",
  AVG(MALE_RATIO) AS "남성(%)",  
  AVG(FEMALE_RATIO) AS "여성(%)"
FROM
  FACT.FACT_COMMERCIAL FC
  JOIN DIM.DIM_AREA DA ON FC.AREA_ID = DA.AREA_ID,
  WEEK_RANGE WR
WHERE
  TO_TIMESTAMP(FC.TIME_KEY::TEXT, 'YYYYMMDDHH24MI') BETWEEN WR.START_OF_LAST_WEEK AND WR.END_OF_LAST_WEEK
GROUP BY
  DA.AREA_NAME
ORDER BY
  CASE
    WHEN {{SORT_BY}} = '남성' THEN AVG(FC.MALE_RATIO)
    WHEN {{SORT_BY}} = '여성' THEN AVG(FC.FEMALE_RATIO)
    ELSE NULL
  END DESC
LIMIT
  5;