WITH
  WEEK_RANGE AS (
    SELECT
      DATE_TRUNC('WEEK', GETDATE()) - INTERVAL '7 DAYS' AS START_OF_LAST_WEEK,
      DATE_TRUNC('WEEK', GETDATE()) - INTERVAL '1 SECOND' AS END_OF_LAST_WEEK
  )
SELECT
  DA.AREA_NAME AS "장소명",
  AVG(MALE_RATIO) AS "남성(%)",
  AVG(FEMALE_RATIO) AS "여성(%)",
  AVG(AGE_10S_RATIO) AS "10대 이하(%)",
  AVG(AGE_20S_RATIO) AS "20대(%)",
  AVG(AGE_30S_RATIO) AS "30대(%)",
  AVG(AGE_40S_RATIO) AS "40대(%)",
  AVG(AGE_50S_RATIO) AS "50대(%)",
  AVG(AGE_60S_RATIO) AS "60대 이상(%)",
  AVG(INDIVIDUAL_CONSUMER_RATIO) AS "개인(%)",
  AVG(CORPORATE_CONSUMER_RATIO) AS "법인(%)"
FROM
  FACT.FACT_COMMERCIAL FC
  JOIN DIM.DIM_AREA DA ON FC.AREA_ID = DA.AREA_ID,
  WEEK_RANGE WR
WHERE
  TO_TIMESTAMP(FC.TIME_KEY::TEXT, 'YYYYMMDDHH24MI') BETWEEN WR.START_OF_LAST_WEEK AND WR.END_OF_LAST_WEEK
GROUP BY
  DA.AREA_NAME
ORDER BY
  CASE
    WHEN {{SORT_BY}} = '10대 이하' THEN AVG(FC.AGE_10S_RATIO)
    WHEN {{SORT_BY}} = '20대' THEN AVG(FC.AGE_20S_RATIO)
    WHEN {{SORT_BY}} = '30대' THEN AVG(FC.AGE_30S_RATIO)
    WHEN {{SORT_BY}} = '40대' THEN AVG(FC.AGE_40S_RATIO)
    WHEN {{SORT_BY}} = '50대' THEN AVG(FC.AGE_50S_RATIO)
    WHEN {{SORT_BY}} = '60대 이상' THEN AVG(FC.AGE_60S_RATIO)
    ELSE NULL
  END DESC
LIMIT
  5;