WITH
  WEEK_RANGE AS (
    SELECT
      DATE_TRUNC('WEEK', GETDATE()) - INTERVAL '7 DAYS' AS START_OF_LAST_WEEK,
      DATE_TRUNC('WEEK', GETDATE()) - INTERVAL '1 SECOND' AS END_OF_LAST_WEEK
  )
SELECT
  DA.AREA_NAME AS "장소명",
  AVG(INDIVIDUAL_CONSUMER_RATIO) AS "개인(%)",
  AVG(CORPORATE_CONSUMER_RATIO) AS "법인(%)"
FROM
  FACT.FACT_COMMERCIAL FC
  JOIN DIM.DIM_AREA DA ON FC.AREA_ID = DA.AREA_ID,
  WEEK_RANGE WR
WHERE
  TO_TIMESTAMP(FC.TIME_KEY::TEXT, 'YYYYMMDDHH24MI') BETWEEN WR.START_OF_LAST_WEEK AND WR.END_OF_LAST_WEEK
GROUP BY
  DA.AREA_NAME
ORDER BY
  CASE
    WHEN {{SORT_BY}} = '개인' THEN AVG(FC.INDIVIDUAL_CONSUMER_RATIO)
    WHEN {{SORT_BY}} = '법인' THEN AVG(FC.CORPORATE_CONSUMER_RATIO)
    ELSE NULL
  END DESC
LIMIT
  5;