WITH
  WEEK_RANGE AS (
    SELECT
      DATE_TRUNC('WEEK', GETDATE()) - INTERVAL '7 DAYS' AS START_OF_PREV_WEEK,
      DATE_TRUNC('WEEK', GETDATE()) - INTERVAL '1 SECONDS' AS END_OF_PREV_WEEK
  ),
  -- 유동 인구 일별 통계 CTE (지난 주 7일)
  DAILY_POPULATION_SUMMARY AS (
    SELECT
      FP.AREA_ID,
      DT.DATE_VALUE,
      ROUND(SUM(POPULATION_MAX)) AS "POPULATION_MAX"
    FROM
      FACT.FACT_POPULATION FP
      JOIN DIM.DIM_TIME DT ON FP.TIME_KEY = DT.TIME_KEY
      JOIN WEEK_RANGE WR ON DT.DATE_VALUE BETWEEN WR.START_OF_PREV_WEEK AND WR.END_OF_PREV_WEEK
    GROUP BY
      DT.DATE_VALUE,
      FP.AREA_ID
    ORDER BY
      FP.AREA_ID
  ),
  DAILY_COMMERCIAL_SUMMARY AS (
    SELECT
      FC.AREA_ID,
      DT.DATE_VALUE,
      ROUND(SUM(TOTAL_PAYMENT_COUNT)) AS "TOTAL_PAYMENT_COUNT",
      ROUND(AVG(PAYMENT_AMOUNT_MAX)) AS "PAYMENT_AMOUNT_MAX"
    FROM
      FACT.FACT_COMMERCIAL FC
      JOIN DIM.DIM_TIME DT ON FC.TIME_KEY = DT.TIME_KEY
      JOIN WEEK_RANGE WR ON DT.DATE_VALUE BETWEEN WR.START_OF_PREV_WEEK AND WR.END_OF_PREV_WEEK
    GROUP BY
      DT.DATE_VALUE,
      FC.AREA_ID
    ORDER BY
      FC.AREA_ID
  )
SELECT
  DA.CATEGORY,
  ROUND(AVG(TOTAL_PAYMENT_COUNT)) AS "일별 평균 결제 건수",
  ROUND((AVG(PAYMENT_AMOUNT_MAX)) / 10000) AS "평균 최대 결제 금액",
  ROUND((AVG(POPULATION_MAX)) / 10000) AS "일별 평균 유동 인구"
FROM
  DAILY_COMMERCIAL_SUMMARY SC
  JOIN DIM.DIM_AREA DA ON SC.AREA_ID = DA.AREA_ID
  JOIN DAILY_POPULATION_SUMMARY SP ON SC.AREA_ID = SP.AREA_ID
GROUP BY
  DA.CATEGORY
ORDER BY
  DA.CATEGORY;