WITH
  WEEK_RANGE AS (
    SELECT
      DATE_TRUNC('WEEK', GETDATE()) - INTERVAL '7 DAYS' AS START_OF_LAST_WEEK,
      DATE_TRUNC('WEEK', GETDATE()) - INTERVAL '1 SECOND' AS END_OF_LAST_WEEK
  ) 
SELECT
  DA.AREA_NAME AS "장소명",
  AVG(POPULATION_MAX) AS "유동 인구",
  AVG(AGE_10S_RATIO) AS "10대 이하(%)",
  AVG(AGE_20S_RATIO) AS "20대(%)",
  AVG(AGE_30S_RATIO) AS "30대(%)",
  AVG(AGE_40S_RATIO) AS "40대(%)",
  AVG(AGE_50S_RATIO) AS "50대(%)",
  AVG(AGE_60S_RATIO) AS "60대 이상(%)"
FROM
  FACT.FACT_POPULATION FP
  JOIN DIM.DIM_AREA DA ON FP.AREA_ID = DA.AREA_ID,
  WEEK_RANGE WR
WHERE
  TO_TIMESTAMP(FP.TIME_KEY::TEXT, 'YYYYMMDDHH24MI') BETWEEN WR.START_OF_LAST_WEEK AND WR.END_OF_LAST_WEEK
GROUP BY
  DA.AREA_NAME
ORDER BY
  CASE
    WHEN {{SORT_BY}} = '10대 이하' THEN AVG(FP.AGE_10S_RATIO)
    WHEN {{SORT_BY}} = '20대' THEN AVG(FP.AGE_20S_RATIO)
    WHEN {{SORT_BY}} = '30대' THEN AVG(FP.AGE_30S_RATIO)
    WHEN {{SORT_BY}} = '40대' THEN AVG(FP.AGE_40S_RATIO)
    WHEN {{SORT_BY}} = '50대' THEN AVG(FP.AGE_50S_RATIO)
    WHEN {{SORT_BY}} = '60대 이상' THEN AVG(FP.AGE_60S_RATIO)
    ELSE NULL
  END DESC
LIMIT
  5;