WITH
  WEEK_RANGE AS (
    SELECT
      DATE_TRUNC('WEEK', GETDATE()) - INTERVAL '7 DAYS' AS START_OF_PREV_WEEK,
      DATE_TRUNC('WEEK', GETDATE()) - INTERVAL '1 SECONDS' AS END_OF_PREV_WEEK
  ),
  -- 유동 인구 일별 통계 CTE (지난 주 7일)
  DAILY_POPULATION_SUMMARY AS (
    SELECT
      FP.AREA_ID,
      DT.DATE_VALUE,
      ANY_VALUE(DT.DAY_NAME),
      ROUND(SUM(POPULATION_MAX)) AS "POPULATION_MAX",
      ROUND(AVG(AGE_10S_RATIO)) AS "AGE_10S_RATIO",
      ROUND(AVG(AGE_20S_RATIO)) AS "AGE_20S_RATIO",
      ROUND(AVG(AGE_30S_RATIO)) AS "AGE_30S_RATIO",
      ROUND(AVG(AGE_40S_RATIO)) AS "AGE_40S_RATIO",
      ROUND(AVG(AGE_50S_RATIO)) AS "AGE_50S_RATIO",
      ROUND(AVG(AGE_60S_RATIO)) AS "AGE_60S_RATIO"
    FROM
      FACT.FACT_POPULATION FP
      JOIN DIM.DIM_TIME DT ON FP.TIME_KEY = DT.TIME_KEY
      JOIN WEEK_RANGE WR ON DT.DATE_VALUE BETWEEN WR.START_OF_PREV_WEEK AND WR.END_OF_PREV_WEEK
    GROUP BY
      DT.DATE_VALUE,
      FP.AREA_ID
    ORDER BY
      FP.AREA_ID
  )
SELECT
  DA.CATEGORY,
  ROUND(AVG(AGE_10S_RATIO)) AS "10대 이하(%)",
  ROUND(AVG(AGE_20S_RATIO)) AS "20대(%)",
  ROUND(AVG(AGE_30S_RATIO)) AS "30대(%)",
  ROUND(AVG(AGE_40S_RATIO)) AS "40대(%)",
  ROUND(AVG(AGE_50S_RATIO)) AS "50대(%)",
  ROUND(AVG(AGE_60S_RATIO)) AS "60대(%)"
FROM
  DAILY_POPULATION_SUMMARY SC
  JOIN DIM.DIM_AREA DA ON SC.AREA_ID = DA.AREA_ID
GROUP BY
  DA.CATEGORY
ORDER BY
  DA.CATEGORY;